### ISSUE TITLE
GHPages don't allow for easy browsing

### ISSUE THREAD

**Issue by SFGrenade** [PrashantMohta/ModdingDocs#3]
there's no overview on like the left to see which pages all exist.

**Comment by SFGrenade** [comment]
Can be done with a ghpages theme:
https://github.com/pmarsceill/just-the-docs
and
https://pmarsceill.github.io/just-the-docs/#getting-started
and
https://github.com/pmarsceill/jtd-remote

**Comment by PrashantMohta** [comment]
Thanks for this suggestion! have gone ahead with [just-the-docs](https://github.com/pmarsceill/just-the-docs) for now!
